
import csv
from collections import Counter
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def generate_report(scored_csv_path, output_pdf_path, title=None):
    with open(scored_csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    total = len(rows)
    decisions = Counter(r.get("decision", "UNKNOWN") for r in rows)
    auto = decisions.get("AUTO_LINK", 0)
    flag = decisions.get("LINK_WITH_FLAG", 0)
    quar = decisions.get("QUARANTINE", 0)

    flagged_rows = [r for r in rows if r.get("decision") in
                    ("LINK_WITH_FLAG", "QUARANTINE")]

    doc = SimpleDocTemplate(
        output_pdf_path, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title=title or "Identity Trust Assessment Report",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=18,
                        textColor=colors.HexColor("#1F3A5F"), spaceAfter=12)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13,
                        textColor=colors.HexColor("#4A6FA5"),
                        spaceBefore=16, spaceAfter=8)
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=9,
                           textColor=colors.HexColor("#6B7280"))

    story = []
    story.append(Paragraph(title or "Identity Trust Assessment Report", h1))
    story.append(Paragraph(
        "Batch evaluation of patient records through a five-dimension "
        "trust assessment layer.", body))
    story.append(Spacer(1, 0.5*cm))

    story.append(Paragraph("Summary", h2))
    summary_data = [
        ["Total records processed", str(total)],
        ["Auto-linked (low risk)", str(auto)],
        ["Flagged for review (medium risk)", str(flag)],
        ["Quarantined (high risk)", str(quar)],
    ]
    summary_table = Table(summary_data, colWidths=[9*cm, 5*cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F3F4F6")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)

    if flagged_rows:
        story.append(Paragraph("Flagged records", h2))
        header = ["Canonical ID", "Name", "Trust", "Decision", "Weakest dimension"]
        table_data = [header]
        for r in flagged_rows[:50]:
            dims = {
                "completeness": float(r.get("dim_completeness", 0) or 0),
                "temporal":     float(r.get("dim_temporal", 0) or 0),
                "identity":     float(r.get("dim_identity", 0) or 0),
                "provenance":   float(r.get("dim_provenance", 0) or 0),
                "cross_record": float(r.get("dim_cross_record", 0) or 0),
            }
            weakest = min(dims, key=dims.get)
            name = (r.get("given_name", "") + " " + r.get("family_name", "")).strip()
            table_data.append([
                r.get("canonical_id", "")[:14],
                name[:22],
                r.get("trust_score", ""),
                r.get("decision", ""),
                weakest,
            ])

        table = Table(table_data, colWidths=[2.8*cm, 4.5*cm, 1.8*cm, 3*cm, 3*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4A6FA5")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D1D5DB")),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(table)
        if len(flagged_rows) > 50:
            story.append(Spacer(1, 0.3*cm))
            story.append(Paragraph(
                "Showing first 50 of " + str(len(flagged_rows)) +
                " flagged records. Full list in the scored CSV.", small))

    story.append(Spacer(1, 1*cm))
    story.append(Paragraph(
        "Generated by the Identity Trust Assessment framework. "
        "Every routing decision traces to a specific DOH Standard clause "
        "in the accompanying audit log.", small))

    doc.build(story)
    return {
        "input": scored_csv_path,
        "output": output_pdf_path,
        "total": total,
        "auto": auto,
        "flagged": flag,
        "quarantined": quar,
    }
